model = "gpt-5.2"
model_reasoning_effort = "low"
sandbox_mode = ""
approval_policy = "never"
preferred_auth_method = "chatgpt"
project_doc_max_bytes = 65536

[features]
web_search_request = false
streamable_shell = false
unified_exec = false
apply_patch_freeform = false
view_image_tool = false
shell_tool = false

[tools]
web_search = false
